src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 75)]
    private ?string $Title = null;

    #[ORM\Column(length: 100)]
    private ?string $MetaTitle = null;

    #[ORM\Column(length: 100)]
    private ?string $Slug = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Summary = null;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $Type = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $SKU = null;

    #[ORM\Column]
    private ?float $Price = null;

    #[ORM\Column(nullable: true)]
    private ?float $Discount = null;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $Quantity = null;

    #[ORM\Column(length: 255)]
    private ?string $Shop = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $CreatedAt = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $UpdatedAt = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $PublishedAt = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $StartsAt = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $EndsAt = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $Content = null;

    #[ORM\ManyToOne(inversedBy: 'Products')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $UserId = null;

    #[ORM\OneToMany(mappedBy: 'Product', targetEntity: Pictures::class)]
    private Collection $Pictures;

    public function __construct()
    {
        $this->Pictures = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getMetaTitle(): ?string
    {
        return $this->MetaTitle;
    }

    public function setMetaTitle(string $MetaTitle): self
    {
        $this->MetaTitle = $MetaTitle;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->Slug;
    }

    public function setSlug(string $Slug): self
    {
        $this->Slug = $Slug;

        return $this;
    }

    public function getSummary(): ?string
    {
        return $this->Summary;
    }

    public function setSummary(string $Summary): self
    {
        $this->Summary = $Summary;

        return $this;
    }

    public function getType(): ?int
    {
        return $this->Type;
    }

    public function setType(int $Type): self
    {
        $this->Type = $Type;

        return $this;
    }

    public function getSKU(): ?string
    {
        return $this->SKU;
    }

    public function setSKU(?string $SKU): self
    {
        $this->SKU = $SKU;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->Price;
    }

    public function setPrice(float $Price): self
    {
        $this->Price = $Price;

        return $this;
    }

    public function getDiscount(): ?float
    {
        return $this->Discount;
    }

    public function setDiscount(?float $Discount): self
    {
        $this->Discount = $Discount;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->Quantity;
    }

    public function setQuantity(int $Quantity): self
    {
        $this->Quantity = $Quantity;

        return $this;
    }

    public function getShop(): ?string
    {
        return $this->Shop;
    }

    public function setShop(string $Shop): self
    {
        $this->Shop = $Shop;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->CreatedAt;
    }

    public function setCreatedAt(\DateTimeImmutable $CreatedAt): self
    {
        $this->CreatedAt = $CreatedAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->UpdatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $UpdatedAt): self
    {
        $this->UpdatedAt = $UpdatedAt;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeImmutable
    {
        return $this->PublishedAt;
    }

    public function setPublishedAt(\DateTimeImmutable $PublishedAt): self
    {
        $this->PublishedAt = $PublishedAt;

        return $this;
    }

    public function getStartsAt(): ?\DateTimeImmutable
    {
        return $this->StartsAt;
    }

    public function setStartsAt(?\DateTimeImmutable $StartsAt): self
    {
        $this->StartsAt = $StartsAt;

        return $this;
    }

    public function getEndAt(): ?\DateTimeImmutable
    {
        return $this->EndsAt;
    }

    public function setEndAt(?\DateTimeImmutable $EndsAt): self
    {
        $this->EndsAt = $EndsAt;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->Content;
    }

    public function setContent(?string $Content): self
    {
        $this->Content = $Content;

        return $this;
    }

    public function getUserId(): ?User
    {
        return $this->UserId;
    }

    public function setUserId(?User $UserId): self
    {
        $this->UserId = $UserId;

        return $this;
    }

    /**
     * @return Collection<int, Pictures>
     */
    public function getPictures(): Collection
    {
        return $this->Pictures;
    }

    public function addPicture(Pictures $picture): self
    {
        if (!$this->Pictures->contains($picture)) {
            $this->Pictures->add($picture);
            $picture->setProduct($this);
        }

        return $this;
    }

    public function removePicture(Pictures $picture): self
    {
        if ($this->Pictures->removeElement($picture)) {
            // set the owning side to null (unless already changed)
            if ($picture->getProduct() === $this) {
                $picture->setProduct(null);
            }
        }

        return $this;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Repository\ProductRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class MainController extends AbstractController
{

    #[Route('/', name: 'app_main')]
    public function index(ProductRepository $productRepository): Response
    {
        
        return $this->render('main/index.html.twig', [
            'newproducts' => $productRepository->findBy([],['PublishedAt' => 'DESC'], 8)
        ]);
    }
}

templates/main/_partials/banner.html.twig
    <!-- BANNER AREA START -->
    <div class="ltn__banner-area mt-40">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-sm-6">
                    <div class="ltn__banner-item">
                        <div class="ltn__banner-img">
                            <a href="shop.html"><img src="img/banner/4.jpg" alt="Banner Image"></a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <div class="ltn__banner-item">
                        <div class="ltn__banner-img">
                            <a href="shop.html"><img src="img/banner/2.jpg" alt="Banner Image"></a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <div class="ltn__banner-item">
                        <div class="ltn__banner-img">
                            <a href="shop.html"><img src="img/banner/5.jpg" alt="Banner Image"></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- BANNER AREA END -->

templates/main/_partials/counter.html.twig
    <!-- COUNTDOWN AREA START -->
    <div class="ltn__countdown-area section-bg-1 bg-image-right mt-70" data-bs-bg="img/bg/2.jpg">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 align-self-center">
                    <div class="ltn__countdown-info ltn__countdown-4-info text-center--- pt-100 pb-100">
                        <div class="section-title-area ltn__section-title-2--- mb-0---">
                            <h6 class="ltn__secondary-color">Deal of the day</h6>
                            <!-- <h1 class="section-title">Hot Deal ! Sale Up To <span>25% Off</span></h1> -->
                            <h1 class="section-title">Shop Your Flower <br>
                                Best Offer- $12</span></h1>
                        </div>
                        <div class="ltn__countdown ltn__countdown-4 mb-15" data-countdown="2021/09/25"></div>
                        <div class="btn-wrapper animated">
                            <a href="shop.html" class="theme-btn-2 btn btn-round">Shop now</a>
                        </div>
                        <div class="countdown-img d-none d-xl-block">
                            <img src="img/bg/3.png" alt="#">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- COUNTDOWN AREA END -->

templates/main/_partials/featured.html.twig
    <!-- FEATURE AREA START ( Feature - 3) -->
    <div class="ltn__feature-area mb-90">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="ltn__feature-item-box-wrap ltn__feature-item-box-wrap-2  ltn__border section-bg-6">
                        <div class="ltn__feature-item ltn__feature-item-8">
                            <div class="ltn__feature-icon">
                                <img src="img/icons/svg/8-trolley.svg" alt="#">
                            </div>
                            <div class="ltn__feature-info">
                                <h4>Free shipping</h4>
                                <p>On all orders over $49.00</p>
                            </div>
                        </div>
                        <div class="ltn__feature-item ltn__feature-item-8">
                            <div class="ltn__feature-icon">
                                <img src="img/icons/svg/9-money.svg" alt="#">
                            </div>
                            <div class="ltn__feature-info">
                                <h4>15 days returns</h4>
                                <p>Moneyback guarantee</p>
                            </div>
                        </div>
                        <div class="ltn__feature-item ltn__feature-item-8">
                            <div class="ltn__feature-icon">
                                <img src="img/icons/svg/10-credit-card.svg" alt="#">
                            </div>
                            <div class="ltn__feature-info">
                                <h4>Secure checkout</h4>
                                <p>Protected by Paypal</p>
                            </div>
                        </div>
                        <div class="ltn__feature-item ltn__feature-item-8">
                            <div class="ltn__feature-icon">
                                <img src="img/icons/svg/11-gift-card.svg" alt="#">
                            </div>
                            <div class="ltn__feature-info">
                                <h4>Offer & gift here</h4>
                                <p>On all orders over</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- FEATURE AREA END -->

templates/main/_partials/newsletter.html.twig
    <!-- NEWSLETTER AREA START -->
    <div class="ltn__newsletter-area section-bg-1 bg-overlay-black-10 bg-image pt-110 pb-90" data-bs-bg="img/bg/3.jpg">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 offset-lg-2">
                    <div class="ltn__newsletter-inner ltn__newsletter-inner-4 text-color-white text-center">
                        <h1>Get The Latest Deals</h1>
                        <h5>$30 coupon for first shopping</h5>
                        <form action="#" class="ltn__form-box">
                            <input type="email" name="email" placeholder="Email*">
                            <div class="btn-wrapper">
                                <button class="theme-btn-1 btn text-uppercase" type="submit">Subscribe</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- NEWSLETTER AREA END -->

templates/main/_partials/product.html.twig
    <!-- PRODUCT AREA START -->
    <div class="ltn__product-area ltn__product-gutter  pt-90 pb-40---">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-title-area text-center">
                        <h1 class="section-title section-title-border">new arrival items</h1>
                    </div>
                </div>
            </div>
            <div class="row justify-content-center">      

                {# {{ dump(newproducts )}} #}
                {% for product in newproducts %}
                {# {{ dump(product.Pictures) }} #}
                <!-- ltn__product-item -->
                <div class="col-lg-3 col-md-4 col-sm-6 col-6">
                    <div class="ltn__product-item text-center">
                        <div class="product-img">
                            <a href="{{ path('app_product', {'slug': product.Slug}) }}">
                                {% for ImageProduit in product.Pictures %}
                                    {% if loop.index0 == 0 %}
                                        <img src="{{ vich_uploader_asset(ImageProduit, 'imageFile') }}" alt="{{ ImageProduit.Alt }}" height="200"></a>
                                    {% endif %}    
                                {% endfor %}
                            {% if product.Discount is not null %}
                            <div class="product-badge">
                                <ul>
                                    <li class="badge-2">{{ product.Discount }}%</li>
                                </ul>
                            </div>
                            {% endif %}

                            <div class="product-hover-action product-hover-action-2">
                                <ul>
                                    <li>
                                        <a href="#" title="Quick View" data-bs-toggle="modal" data-bs-target="#quick_view_modal">
                                            <i class="icon-magnifier"></i>
                                        </a>
                                    </li>
                                    <li class="add-to-cart">
                                        <a href="{{ path('cart_index', {'id': product.Id}) }}" title="Add to Cart" data-bs-toggle="modal" data-bs-target="#add_to_cart_modal">
                                            <span class="cart-text d-none d-xl-block">Add to Cart</span>
                                            <span class="d-block d-xl-none"><i class="icon-handbag"></i></span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#" title="Quick View" data-bs-toggle="modal" data-bs-target="#quick_view_modal">
                                            <i class="icon-shuffle"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>

                            {% set DateJour = "now"|date("Y/m/d") %}

                            {% if product.EndAt|date("Y/m/d") > DateJour %}
                            <div class="ltn__product-countdown">
                                <div class="ltn__countdown" data-countdown="{{ product.EndAt|date("Y/m/d") }}"></div>
                            </div>
                            {% endif %}

                        </div>
                        <div class="product-info">
                            <h2 class="product-title">
                                <a href="{{ path('app_product', {'slug': product.Slug}) }}">
                                    {{ product.Title }}
                                </a>
                            </h2>
                            <div class="product-price">
                            {% if product.Discount is null %}
                                <span>${{ product.Price }}</span>
                            {% endif %}
                            {% if product.Discount is not null %}
                                <span>${{ product.Price - (product.price * product.discount / 100) }}</span>
                                <del>${{ product.Price }}</del>
                            {% endif %}   

                            </div>
                        </div>
                    </div>
                </div>   
                {% endfor %}

            </div>
        </div>
    </div>
    <!-- PRODUCT SLIDER AREA END -->

templates/main/_partials/slider.html.twig
    <!-- SLIDER AREA START (slider-4) -->
    <div class="ltn__slider-area ltn__slider-4 position-relative">
        <div class="ltn__slide-one-active----- slick-slide-arrow-1----- slick-slide-dots-1----- arrow-white----- ltn__slide-animation-active">
            
            <!-- HTML5 VIDEO -->
            <video autoplay muted loop id="myVideo">
                <source src="{{ asset('media/1.mp4') }}" type="video/mp4">
            </video>

            <!-- YouTube VIDEO -->
            <!-- <div class="ltn__youtube-video-background">
                <iframe frameborder="0" height="100%" width="100%"
                  src="https://www.youtube.com/embed/9DYl-nKrQ0k?playlist=9DYl-nKrQ0k&loop=1&controls=0&showinfo=0&autoplay=1&mute=1">
                </iframe>
            </div> -->

            <!-- ltn__slide-item -->
            <div class="ltn__slide-item ltn__slide-item-2 ltn__slide-item-7 bg-image--- bg-overlay-theme-black-30" data-bs-bg="img/slider/41.jpg">
                <div class="ltn__slide-item-inner text-center">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-12 align-self-center">
                                <div class="slide-item-info">
                                    <div class="slide-item-info-inner ltn__slide-animation">
                                        <h6 class="slide-sub-title white-color animated">Flower & Gift</h6>
                                        <h1 class="slide-title text-uppercase white-color animated ">Perfect Bunch <br>For Every Occasion</h1>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- SLIDER AREA END -->

templates/main/_partials/teams.html.twig
    <!-- TEAM AREA START (Team - 3) -->
    <div class="ltn__team-area pt-110--- pb-25">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-title-area text-center">
                        <h1 class="section-title section-title-border">our team</h1>
                    </div>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-xl-3 col-lg-4 col-sm-6">
                    <div class="ltn__team-item ltn__team-item-4">
                        <div class="team-img">
                            <img src="img/team/1.jpg" alt="Image">
                        </div>
                        <div class="team-info">
                            <h5>RWilliam Gabriel</h5>
                            <h6>Team Expart</h6>
                            <div class="ltn__social-media">
                                <ul>
                                    <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                                    <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                                    <li><a href="#"><i class="fab fa-pinterest-p"></i></a></li>
                                    <li><a href="#"><i class="fab fa-instagram"></i></a></li>
                                    <li><a href="#"><i class="fab fa-dribbble"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-4 col-sm-6">
                    <div class="ltn__team-item ltn__team-item-4">
                        <div class="team-img">
                            <img src="img/team/2.jpg" alt="Image">
                        </div>
                        <div class="team-info">
                            <h5>Kelian Anderson</h5>
                            <h6>Team Expart</h6>
                            <div class="ltn__social-media">
                                <ul>
                                    <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                                    <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                                    <li><a href="#"><i class="fab fa-pinterest-p"></i></a></li>
                                    <li><a href="#"><i class="fab fa-instagram"></i></a></li>
                                    <li><a href="#"><i class="fab fa-dribbble"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-4 col-sm-6">
                    <div class="ltn__team-item ltn__team-item-4">
                        <div class="team-img">
                            <img src="img/team/3.jpg" alt="Image">
                        </div>
                        <div class="team-info">
                            <h5>James Carter </h5>
                            <h6>Team Expart</h6>
                            <div class="ltn__social-media">
                                <ul>
                                    <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                                    <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                                    <li><a href="#"><i class="fab fa-pinterest-p"></i></a></li>
                                    <li><a href="#"><i class="fab fa-instagram"></i></a></li>
                                    <li><a href="#"><i class="fab fa-dribbble"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-4 col-sm-6">
                    <div class="ltn__team-item ltn__team-item-4">
                        <div class="team-img">
                            <img src="img/team/4.jpg" alt="Image">
                        </div>
                        <div class="team-info">
                            <h5>Adam Joseph</h5>
                            <h6>Team Expart</h6>
                            <div class="ltn__social-media">
                                <ul>
                                    <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                                    <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                                    <li><a href="#"><i class="fab fa-pinterest-p"></i></a></li>
                                    <li><a href="#"><i class="fab fa-instagram"></i></a></li>
                                    <li><a href="#"><i class="fab fa-dribbble"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- TEAM AREA END -->